const ENDPOINTS = {
  CheckNumberAvailable: 'api/v1/numbers/check',
  ReserveSpecificNumber: 'api/v1/numbers/reserve',
  GoogleSignin: 'api/v1/auth/google',
  GetUserProfile: 'api/v1/auth/profile',
  RefreshToken: 'api/v1/auth/refresh',
  AppleSignin: 'api/v1/auth/apple',
  UpdateFCMToken: 'api/v1/auth/fcm-token',
  RandomNumberReservation: 'api/v1/numbers/reserve',
  GetRandomNumber: 'api/v1/numbers/random',
  GetStripePlans: 'api/v1/subscription/plans',
  StripeConfig: 'api/v1/subscription/stripe-config',
  CreateSetupIntent: 'api/v1/subscription/setup-intent',
  CreateApplePaySetupIntent: 'api/v1/subscription/apple-pay/setup-intent',
  CreateExternalPaymentCheckoutLink: 'api/v1/subscription/checkout-session',
  ConfirmSetupIntent: 'api/v1/subscription/confirm-setup-intent',
  ConfirmApplePaySetupIntent:
    '/api/v1/subscription/apple-pay/confirm-setup-intent',
  CollectBadges: 'api/v1/badges/claim',
  GetBlogForUser: 'api/v1/blogs',
  GetBlogById: 'api/v1/blogs',
  LikeUnlikeBlog: 'api/v1/blogs',
  AddCommentToBlog: 'api/v1/blogs',
  ShareBlog: 'api/v1/blogs',
  GetArtForUser: 'api/v1/art',
  GetArtById: 'api/v1/art',
  CommentsOnArt: 'api/v1/art',
  LikeUnlikeArt: 'api/v1/art',
  ShareArt: 'api/v1/art',
  GetArtComments: 'api/v1/art',
  GetBlogComments: 'api/v1/blogs',
  GetUserReceipts: 'api/v1/receipts',
  GetAllBadges: 'api/v1/badges/all',
  ViewedBadges: 'api/v1/badges/mark-viewed',
  UpdatePlan: 'api/v1/subscription/update-plan',
  resubscribePlan: 'api/v1/subscription/resubscribe',
  cancelPlan: 'api/v1/subscription/cancel',
  RemainingSpots: 'api/v1/numbers/available-spots',
  mySubscription: 'api/v1/subscription/my-subscription',
  storeFcmTokenDuringOnBoarding: '/api/v1/onboarding/fcm-token',
  DeleteAccount: 'api/v1/auth/delete-account',
  DemoStatus: 'api/v1/auth/demo-status',
  DemoLogin: 'api/v1/auth/demo-login',
};

export default ENDPOINTS;
