const IMAGES = {
  KidsImage: require("./KidsImage.png"),
  kidsImageOne: require("./Kidsimage1.png"),
  Image: require("./Image.png"),
  MissionImage: require("./MissionImage.png"),
  JoinImage: require("./JoinImage.png"),
  OnePaliLogo: require("./OnePaliLogo.png"),
  Paliroot: require("./Paliroot.png"),
  MecaImage: require("./MecaImage.png"),
  ClaimCard: require("./ClaimCard.png"),
  SupportImage: require("./SupportImage.png"),
  LoopImage: require("./LoopImage.png"),
  GetStartedImage: require("./GetStartedImage.png"),
  GetStartedBottomImage: require("./getStartedBottomImage.png"),
  LogoText: require("./LogoText.png"),
  BadgeGreenBg: require("./BadgeGreenBg.png"),
  BadgeBrownBg: require("./BadgeBrownBg.png"),
  BadgePinkBg: require("./BadgePinkBg.png"),
  BadgeBlackBg: require("./BadgeBlackBg.png"),
  ImageLike: require("./ImageLike.png"),
  SplashInitial: require("./SplashInitial.png"),
  HomeTextBackgorund: require("./HomeTextBackgorund.png"),
  EarnBadgs: require("./EarnBadges.png"),
  NumberChoose: require("./NumberChoose.png"),
  twiceImage: require("./twiceImage.png"),
  thriceImage: require("./thriceImage.png"),
  CharityNavigator: require("./CharityNavigator.png"),
  middleEast: require("./middleEast.png"),
  progressImage: require("./ProgressBar.png"),
  SplashBackground: require("./SplashBackground.png"),
  PeoplesImage: require("./PeoplesImage.png"),
  LogoOnepali: require("./LogoOnepali.png"),
  NewSplashImage: require("./NewSplash.png"),
  Carousel1: require("./Carousel1.png"),
  Carousel2: require("./Carousel2.png"),
  Carousel3: require("./Carousel3.png"),
  Carousel4: require("./Carousel4.png"),
  Carousel5: require("./Carousel5.png"),
  Carousel6: require("./Carousel6.png"),
  Carousel7: require("./Carousel7.png"),
  Carousel8: require("./Carousel8.png"),
  MECA: require("./MECA.png"),
  PeoplesDonating: require("./PeoplesDonating.png"),
};

export default IMAGES;
