const FONTS = {
  regular: 'kodeMono-Regular',
  bold: 'kodeMono-Bold',
  semiBold: 'kodeMono-SemiBold',
  medium: 'kodeMono-Medium',
  GabaritoBlack: 'Gabarito-Black',
  GabaritoBold: 'Gabarito-Bold',
  GabaritoExtraBold: 'Gabarito-ExtraBold',
  GabaritoSemiBold: 'Gabarito-SemiBold',
  GabaritoMedium: 'Gabarito-Medium',
  GabaritoRegular: 'Gabarito-Regular',
  MontserratBlack: 'Montserrat-Black',
  MontserratBlackItalic: 'Montserrat-BlackItalic',
  MontserratBold: 'Montserrat-Bold',
  MontserratSemiBold: 'Montserrat-SemiBold',
  MontserratMedium: 'Montserrat-Medium',
  MontserratRegular: 'Montserrat-Regular',
  MontserratBoldItalic: 'Montserrat-BoldItalic',
  MontserratSemiBoldItalic: 'Montserrat-SemiBoldItalic',
  MontserratMediumItalic: 'Montserrat-MediumItalic',
  MontserratRegularItalic: 'Montserrat-RegularItalic',
  MontserratExtraBold: 'Montserrat-ExtraBold',
  MontserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
  MontserratExtraLight: 'Montserrat-ExtraLight',
  MontserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
  MontserratItalic: 'Montserrat-Italic',
  MontserratLight: 'Montserrat-Light',
  MontserratLightItalic: 'Montserrat-LightItalic',
  MontserratThin: 'Montserrat-Thin',
  MontserratThinItalic: 'Montserrat-ThinItalic',
  NeueMontrealbold: 'NeueMontreal-Bold',
  NeueMontrealboldItalic: 'NeueMontreal-BoldItalic',
  NeueMontrealitalic: 'NeueMontreal-Italic',
  NeueMontreallight: 'NeueMontreal-Light',
  NeueMontreallightItalic: 'NeueMontreal-LightItalic',
  NeueMontrealmedium: 'NeueMontreal-Medium',
  NeueMontrealmediumItalic: 'NeueMontreal-MediumItalic',
  NeueMontrealregular: 'NeueMontreal-Regular',
  SourceSansBlack : 'SourceSans3-Black',
  SourceSansBlackItalic : 'SourceSans3-BlackItalic',
  SourceSansBold : 'SourceSans3-Bold',
  SourceSansBoldItalic : 'SourceSans3-BoldItalic',
  SourceSansExtraBold : 'SourceSans3-ExtraBold',
  SourceSansExtraBoldItalic : 'SourceSans3-ExtraBoldItalic',
  SourceSansExtraLight : 'SourceSans3-ExtraLight',
  SourceSansExtraLightItalic : 'SourceSans3-ExtraLightItalic',
  SourceSansItalic : 'SourceSans3-Italic',
  SourceSansLight : 'SourceSans3-Light',
  SourceSansLightItalic : 'SourceSans3-LightItalic',
  SourceSansMedium : 'SourceSans3-Medium',
  SourceSansMediumItalic : 'SourceSans3-MediumItalic',
  SourceSansRegular : 'SourceSans3-Regular',
  SourceSansSemiBold : 'SourceSans3-SemiBold',
  SourceSansSemiBoldItalic : 'SourceSans3-SemiBoldItalic',
};

export default FONTS;

export type FontFamilyType = keyof typeof FONTS;
